benchmarks/urls.py
from django.conf.urls import include, url

from .drest import router as drest_router
from .drf import router as drf_router

urlpatterns = [
    url(r'^', include(drf_router.urls)),
    url(r'^', include(drest_router.urls)),
]

dynamic_rest/urls.py
"""
Login and logout views for the admin API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""  # noqa
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views
from dynamic_rest.conf import settings as drest

template_name = {'template_name': drest.ADMIN_LOGIN_TEMPLATE}

app_name = 'dynamic_rest'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

benchmarks/models.py
from django.db import models


class User(models.Model):
    name = models.TextField()
    groups = models.ManyToManyField('Group', related_name='users')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Group(models.Model):
    name = models.TextField()
    max_size = models.PositiveIntegerField()
    permissions = models.ManyToManyField('Permission', related_name='groups')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


class Permission(models.Model):
    name = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

dynamic_rest/views.py
from __future__ import absolute_import
from django.contrib.auth import views
from dynamic_rest.conf import settings


def login(request):
    template_name = settings.ADMIN_LOGIN_TEMPLATE
    return views.login(request, template_name=template_name)


def logout(request):
    return views.logout(request)

dynamic_rest/blueprints/api/templates/{{app}}/api/urls.py.j2
from djx.urls import load_urls
urlpatterns = load_urls(__file__)

dynamic_rest/blueprints/api/templates/{{app}}/api/{{version}}/serializers/__init__.py.j2
from .{{name}} import {{serializer_class_name}}

dynamic_rest/blueprints/api/templates/{{app}}/api/{{version}}/serializers/base.py.j2
from dynamic_rest.serializers import DynamicModelSerializer

class Serializer(DynamicModelSerializer):
    pass

dynamic_rest/blueprints/api/templates/{{app}}/api/{{version}}/serializers/{{name}}.py.j2
from .base import Serializer
from {{app}}.models import {{model_class_name}}

class {{serializer_class_name}}(Serializer):
    class Meta:
        model = {{model_class_name}}
        name = '{{name}}'
        plural_name = '{{plural_name}}'
        fields = ('id', )

dynamic_rest/blueprints/api/templates/{{app}}/api/{{version}}/urls.py.j2
from . import views
from dynamic_rest.routers import DynamicRouter
from inspect import isclass

router = DynamicRouter()
for name in dir(views):
    view = getattr(views, name, None)
    if (
        isclass(view) and
        hasattr(view, 'get_serializer_class')
    ):
        view_instance = view()
        serializer = view_instance.get_serializer_class()
        plural_name = serializer.get_plural_name()
        name = serializer.get_name()
        router.register(
            r'%s' % plural_name,
            view,
            name,
            namespace='{{version}}'
        )

urlpatterns = router.urls

dynamic_rest/blueprints/api/templates/{{app}}/api/{{version}}/views/__init__.py.j2
from .{{name}} import {{viewset_class_name}}

dynamic_rest/blueprints/api/templates/{{app}}/api/{{version}}/views/base.py.j2
from dynamic_rest.viewsets import DynamicModelViewSet

class ViewSet(DynamicModelViewSet):
    pass

dynamic_rest/blueprints/api/templates/{{app}}/api/{{version}}/views/{{name}}.py.j2
from ..serializers import {{serializer_class_name}}
from .base import ViewSet
from {{app}}.models import {{model_class_name}}

class {{viewset_class_name}}(ViewSet):
    serializer_class = {{serializer_class_name}}
    model = {{model_class_name}}
    queryset = {{model_class_name}}.objects.all()

dynamic_rest/blueprints/init/templates/{{app}}/settings.py.j2
INSTALLED_APPS = [
    'dynamic_rest',
    'rest_framework'
]

dynamic_rest/templates/dynamic_rest/admin/detail.html
{% load rest_framework %}
{% load dynamic_rest %}

<form
    id="drest-edit-form"
    class="drest-form drest-form--readonly drest-form--edit"
    action="{{ request.get_full_path }}"
    method="PATCH">
    <div class="drest-grid">
            {% get_sections results.serializer as sections %}
            {% for section in sections %}
                <div class="drest-grid__item">
                    <div class="drest-section mdc-card {% if section.field %}mdc-card--solo{% endif %}">
                        {% if section.name %}
                            <div class="mdc-card__title">{{ section.name }}</div>
                        {% endif %}
                        <div class="mdc-card__fields">
                            {% for field in section.fields %}
                                {% if field.should_render %}
                                    {% render_field field style=render_style %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
    <input class="drest-hidden" type="submit"/>
</form>
<script>
    new DRESTForm({
        container: '#drest-edit-form',
        type: 'edit',
        resourceName: '{{ singular_name }}'
    });
</script>

dynamic_rest/templates/dynamic_rest/admin/directory.html
{% load rest_framework %}
{% load dynamic_rest %}
{% drest_settings 'ADMIN_ICON_PACK' as icons %}

<div class="drest-directory mdc-list">
{% for key, value in directory.items %}
    {% with url=value.0 icon=value.1 %}
            <a class="mdc-list-item" href="{{ url }}">
                {% if icon %}
                    <span class="drest-icon-left {{ icons }} {{ icons }}-{{ icon }}"></span>
                {% endif %}
                <span>{{ key }}</span>
            </a>
    {% endwith %}
{% endfor %}
</div>

dynamic_rest/templates/dynamic_rest/admin/error.html
<div class="drest-form">
<div class="drest-grid--1x drest-grid">
<div class="drest-grid__item">
<div class="drest-section mdc-card">
    <div class="mdc-card__title">Error</div>
    <div class="mdc-card__fields">
        {{ results.detail }}
    </div>
</div>
</div>
</div>
</div>

dynamic_rest/templates/dynamic_rest/admin/list.html
{% load rest_framework %}
{% load dynamic_rest %}

{% if results %}
    <table id="drest-table" class="table drest-table">
      <thead>
        <tr>
            {% for column in columns %}
                {% get_value_from_dict fields column as field %}
                {% get_sort_query_value field sorted_field sorted_ascending as sort_query_value %}
                {% if field %}
                    <th class="{% if column in sortable_fields %}drest-goto{% endif %} drest-table__header"
                        data-goto='{% replace_query_param url "sort[]" sort_query_value %}'
                    >
                        <div class="drest-table__header-inner">
                            {{ field.label }}
                            {% if column in sortable_fields %}
                                    {% if column == sorted_field %}
                                        <span class="material-icons">
                                            arrow_drop_{% if sorted_ascending %}up{% else %}down{% endif %}
                                        </span>
                                    {% endif %}
                            {% endif %}
                        </div>
                    </th>
                {% else %}
                    <th>{{ column }}</th>
                {% endif %}
            {% endfor %}
        </tr>
      </thead>
      <tbody>
            {% for row in results %}
              <tr>
                {% for key in columns %}
                    {% get_field_value row.serializer row.instance key as field %}
                    <td>{{ field | render_field_value }}</td>
                {% endfor %}
              </tr>
            {% endfor %}
      </tbody>
    </table>
{% else %}
    <div class="drest-error">
        <span class="mdi mdi-alert-circle-outline"></span> No results
    </div>
{% endif %}

dynamic_rest/templates/dynamic_rest/form/checkbox.html
{% load dynamic_rest %}

<div id="{{ field.id }}" title="{{ field.help_text | help_text_format }}" class="drest-field drest-field--checkbox">
    <div class="mdc-form-field mdc-form-field--align-end">

        <div class="mdc-checkbox {% if field.errors %}has-error{% endif %}" data-mdc-auto-init="MDCCheckbox">
            <input
                class="mdc-checkbox__native-control"
                type="checkbox"
                name="{{ field.name }}"
                id="{{ field.id }}-input"
                {% if field.value %}
                    checked
                {% endif %}
                {% if field.read_only %}
                    disabled
                {% endif %}
            >

             <div class="mdc-checkbox__background">
               <svg class="mdc-checkbox__checkmark"
                  viewBox="0 0 24 24">
                 <path class="mdc-checkbox__checkmark-path"
                    fill="none"
                    d="M1.73,12.91 8.1,19.28 22.79,4.59"/>
               </svg>
                <div class="mdc-checkbox__mixedmark"></div>
             </div>
        </div>
        <label for="{{ field.id }}-input" class="drest-label--block">{{ field.label }}{% if field.required %} *{% endif %}</label>
    </div>
    <p
        id="{{ field.id }}-helper"
        class="drest-field__helper">
        {% if field.help_text %}
            {{ field.help_text | help_text_format | safe }}
        {% endif %}
    </p>
    {% include "./field-js.html" %}
</div>

dynamic_rest/templates/dynamic_rest/form/datetime.html
{% load dynamic_rest %}

<div id="{{ field.id }}" class="{% if field.read_only %} drest-field--disabled{% endif %}{% if not field.is_empty %} drest-field--selected{% endif %} drest-field--datetime drest-field{% if field.errors %} drest-field--invalid{% endif %}">
    <div
        class="drest-field__body">
        <input
            id="{{ field.id }}-input"
            name="{{ field.name }}"
            data-type="{{ style.input_type }}"
            class="drest-field__input"
            type="text"
            {% if style.placeholder %}placeholder="{{ style.placeholder }}"{% endif %}
            {% if field.value %}value="{{ field.value }}"{% endif %}
            {% if field.errors %}
                invalid
            {% endif %}
            {% if field.required %}
                required
            {% endif %}
            {% if style.autofocus and style.input_type != "hidden" %}autofocus{% endif %}/>
        <label
            class="drest-label"
            for="{{ field.id }}-input">
            {{ field.label }}
        </label>
        <div class="mdc-line-ripple" data-mdc-auto-init="MDCLineRipple"></div>
    </div>
    <p
        id="{{ field.id }}-helper"
        class="drest-field__helper">
        {% if field.help_text %}
            {{ field.help_text | help_text_format | safe }}
        {% endif %}
    </p>
    {% include "./field-js.html" %}
</div>

dynamic_rest/templates/dynamic_rest/form/field-js.html
{% load dynamic_rest %}

<script>
    var field = new drest.DRESTField({
        id: "{{ field.id }}",
        label: {{ field.label | to_json }},
        readOnly: {{ field.read_only | to_json }},
        writeOnly: {{ field.write_only | to_json }},
        helpText: "{{ field.help_text | help_text_format | escapejs }}",
        depends: {{ field.depends | to_json }},
        helpTextShort: "{{ field.help_text | help_text_short_format | escapejs }}",
        type: {{ field.type | to_json }},
        many: {{ field.many | to_json }},
        name: {{ field.name | to_json }},
        chart: {{ field.chart | to_json }},
        numDigits: {{ field.num_digits | to_json }},
        required: {{ field.required | to_json }},
        deferred: {{ field.deferred | to_json }},
        choices: {{ field.choices | to_json }},
        value: {{ field | field_to_json }}{% if field.type == 'relation' %},
        relation: {
            nameField: {{ field.get_name_field | to_json }},
            searchKey: {{ field.get_search_key | to_json }},
            pkField: {{ field.get_pk_field | to_json }},
            resourceName: {{ field.serializer.get_name | to_json }},
            pluralName: {{ field.get_plural_name | to_json }},
            url: {{ field.get_url | to_json }},
            image: {% if field.image %}true{% else %}false{% endif %},
            create: {{ field.create | to_json }},
            filter: {{ field.filter | to_json }},
        }
        {% endif %}
    });
</script>

dynamic_rest/templates/dynamic_rest/form/fieldset.html
{% load rest_framework %}
<fieldset>
  {% for nested_field in field %}
    {% if not nested_field.read_only %}
      {% render_field nested_field style=style %}
    {% endif %}
  {% endfor %}
</fieldset>

dynamic_rest/templates/dynamic_rest/form/file.html
{% load dynamic_rest %}

<div id="{{ field.id }}" class="drest-field--file drest-field {% if field.errors %}drest-field--invalid{% endif %}">
    <div class="drest-field__block">
        <label for="{{ field.id }}-input" class="drest-label">
            {{ field.label }}
        </label>
        <input
            id="{{ field.id }}-input"
            name="{{ field.name }}"
            type="file"
            {% if field.value %}
                value="{{ field.value }}"
                data-default-file="{{ field.value.url }}"
            {% endif %}
            {% if field.errors or field.help_text %}
                aria-controls="{{ field.id }}-helper"
                aria-describedby="{{ field.id }}-helper"
            {% endif %}
            {% if field.errors %}
                invalid
            {% endif %}
            {% if field.required and not field.allow_null %}
                required
            {% endif %}
            {% if field.read_only %}
                disabled
            {% endif %}
        >
    </div>
    <p
        id="{{ field.id }}-helper"
        class="drest-field__helper">
        {% if field.help_text %}
            {{ field.help_text | help_text_format | safe }}
        {% endif %}
    </p>
    {% include "./field-js.html" %}
</div>

dynamic_rest/templates/dynamic_rest/form/form.html
{% load rest_framework %}
{% load dynamic_rest %}

{% get_sections form as sections %}
<div class="drest-grid">
        {% for section in sections %}
              <div class="drest-grid__item">
                <div class="drest-section mdc-card {% if section.field %}mdc-card--relation{% endif %}">
                    {% if section.name %}
                        <div class="mdc-card__title">{{ section.name }}</div>
                    {% endif %}

                    {% if section.should_render %}
                        <div class="mdc-card__fields">
                            {% for field in section.fields %}
                                {% if field.should_render %}
                                    {% render_field field style=style %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}
               </div>
            </div>
    {% endfor %}
</div>
<input class="drest-hidden" type="submit"/>

dynamic_rest/templates/dynamic_rest/form/input.html
{% load dynamic_rest %}

<div
    id="{{ field.id }}"
    class="drest-field drest-field--text
    {% if field.errors %}drest-field--invalid{% endif %}
    {% if field.read_only %}drest-field--disabled{% endif %}
    {% if field.write_only %}drest-field--writeonly{% endif %}">

    <div {% if field.iframe %}
            class="drest-field__block">
            <iframe src="{{ field.value }}"></iframe>
        {% else %}
            {% if field.chart %}
                class="drest-field__block">
                <div id="{{ field.id }}-chart" class="drest-chart"></div>
            {% else %}
                class="drest-field__body">
                {% if field.long %}
                    <textarea
                        rows=1
                        name="{{field.name}}"
                        id="{{field.id}}-input" class="drest-field__input"
                        {% if field.read_only %}readonly{% endif %}
                        {% if field.errors or field.help_text %}
                            aria-controls="{{ field.id }}-helper"
                            aria-describedby="{{ field.id }}-helper"
                        {% endif %}
                        {% if field.errors %}invalid{% endif %}
                        {% if field.required %}required{% endif %}
                    >{{ field.value }}</textarea>
                {% else %}
                    <input
                        class="drest-field__input"
                        name="{{ field.name }}"
                        type="{% if style.input_type %}{{ style.input_type}}{% else %}text{% endif %}"
                        id="{{ field.id }}-input"
                        {% if field.read_only %}readonly{% endif %}
                        {% if field.errors or field.help_text %}
                            aria-controls="{{ field.id }}-helper"
                            aria-describedby="{{ field.id }}-helper"
                        {% endif %}
                        {% if field.errors %}invalid{% endif %}
                        {% if field.required %}required{% endif %}
                        value={{ field | field_to_json }}
                    />
                {% endif %}
            {% endif %}
        {% endif %}
        <label
            class="drest-label"
            for="{{ field.id }}-input"
        >
            {{ field.label }}
        </label>
        {% if not field.iframe and not field.chart %}
            <div class="mdc-line-ripple" data-mdc-auto-init="MDCLineRipple"></div>
        {% endif %}
    </div>
    <p
        id="{{ field.id }}-helper"
        class="drest-field__helper">
        {% if field.help_text %}
            {{ field.help_text | help_text_format | safe }}
        {% endif %}
    </p>
    {% include "./field-js.html" %}
</div>

dynamic_rest/templates/dynamic_rest/form/list.html
{% load i18n %}
{% load rest_framework %}
{% load dynamic_rest %}

{% trans "No items to select." as no_items %}

<div id="{{ field.id }}" class="drest-field drest-field--select2 many {% if field.errors %}drest-field--invalid{% endif %}">
    <label for="{{ field.id }}-input" class="drest-label">{{ field.label }}</label>

    <div class="drest-field__body">
        <select
            id="{{ field.id }}-input"
            multiple="multiple"
            class="drest-field__input"
            {% if field.read_only %}disabled{% endif %}
            name="{{ field.name }}">
        </select>
        <div class="mdc-line-ripple" data-mdc-auto-init="MDCLineRipple"></div>
    </div>

    <p
        id="{{ field.id }}-helper"
        class="drest-field__helper">
        {% if field.help_text %}
            {{ field.help_text | help_text_format | safe }}
        {% endif %}
    </p>
    {% include "./field-js.html" %}
</div>

dynamic_rest/templates/dynamic_rest/form/relation.html
{% load i18n %}
{% load rest_framework %}
{% load dynamic_rest %}

{% if field.image %}
    {% get_image_url field as image_url %}
    <div id="{{ field.id }}" class="drest-field--file drest-field--relation drest-field{% if image_url %} drest-field--selected{% endif %}{% if field.errors %} drest-field--invalid{% endif %}{% if field.read_only %} drest-field--disabled{% endif %}">
        <label for="{{ field.id }}" class="drest-label">{{ field.label }}</label>
        <input type="hidden" value={{ field | field_to_json }} id="{{field.id}}-input">
        <div class="dropify-wrapper">
            <div class="dropify-message">
                <span class="material-icons medium">image</span>
            </div>
            <div class="dropify-preview">
                <span class="dropify-render">
                    <img src="{% get_image_url field %}" />
                </span>
            </div>
        </div>
        {% include "./field-js.html" %}
    </div>

{% else %}

    {% trans "No items to select." as no_items %}

    <div id="{{ field.id }}" class="drest-field--relation drest-field--relation drest-field--select2 drest-field{% if field.many %} many{% endif %}{% if field.errors %} drest-field--invalid{% endif %}{% if field.read_only %} drest-field--disabled{% endif %}">
        <label for="{{ field.id }}-input" class="drest-label">{{ field.label }}</label>

        <div class="drest-field__body">
            <select
                class='drest-field__input'
                id="{{ field.id }}-input"
                {% if field.many %}multiple="multiple"{% endif %}
                {% if field.read_only %}disabled{% endif %}
                name="{{ field.name }}">
            </select>
            <div class="mdc-line-ripple" data-mdc-auto-init="MDCLineRipple"></div>
        </div>

        {% if field.add %}
            <div class="drest-field__menu">
                <div
                    class="mdc-icon-button material-icons drest-app__switch-to"
                    data-target="#drest-add-form-{{ field.name }}">
                    add
                </div>
            </div>
        {% endif %}
        <p
            id="{{ field.id }}-helper"
            class="drest-field__helper">
            {% if field.help_text %}
                {{ field.help_text | help_text_format | safe }}
            {% endif %}
        </p>

        {% include "./field-js.html" %}
    </div>


{% endif %}

dynamic_rest/templates/dynamic_rest/form/select.html
{% load rest_framework %}
{% load dynamic_rest %}

<div id="{{ field.id }}" class="drest-field drest-field--select {% if field.read_only %}drest-field--disabled{% endif%}
{% if field.errors %}drest-field--invalid{% endif %}">
    <div class="drest-field__body">
        <select
            {% if field.required and not field.allow_null %}required{% endif %}
            id="{{ field.id }}-input"
            class="drest-field__input"
            {% if field.errors %}
                invalid
            {% endif %}
            {% if field.required and not field.allow_null %}
                required
            {% endif %}
            name="{{ field.name }}"
        >
          {% if field.required and not field.allow_null %}
            {% if not field.value %}
                <option value="" selected disabled></option>
            {% endif %}
          {% else %}
            <option value="" {% if not field.value %}selected{% endif %}>
            </option>
          {% endif %}

          {% for select in field.iter_options %}
              {% if select.start_option_group %}
                <optgroup label="{{ select.label }}">
              {% elif select.end_option_group %}
                </optgroup>
              {% else %}
                <option value="{{ select.value }}" {% if select.value|as_string == field.value|as_string %}selected{% endif %} {% if select.disabled %}disabled{% endif %}>{{ select.display_text }}</option>
              {% endif %}
          {% endfor %}
        </select>
      <label class="drest-label" for="{{ field.id }}-input">
        {{ field.label }}
      </label>
      <div class="mdc-line-ripple" data-mdc-auto-init="MDCLineRipple"></div>
    </div>
    <p
        id="{{ field.id }}-helper"
        class="drest-field__helper">
        {% if field.help_text %}
            {{ field.help_text | help_text_format | safe }}
        {% endif %}
    </p>
{% include "./field-js.html" %}
</div>

dynamic_rest/templates/dynamic_rest/form/textarea.html
{% load dynamic_rest %}

<div
    id="{{ field.id }}"
    class="drest-field
    {% if field.errors %}drest-field--invalid{% endif %}
    {% if field.read_only %}drest-field--disabled{% endif %}
    {% if field.write_only %}drest-field--writeonly{% endif %}">

    <div
        class="drest-field__body">
        {% if field.long %}
            <textarea
                rows=1
                name="{{field.name}}"
                id="{{field.id}}-input" class="drest-field__input"
                {% if field.read_only %}disabled{% endif %}
                {% if field.errors or field.help_text %}
                    aria-controls="{{ field.id }}-helper"
                    aria-describedby="{{ field.id }}-helper"
                {% endif %}
                {% if field.errors %}invalid{% endif %}
                {% if field.required %}required{% endif %}
            >{{ field.value }}</textarea>
        {% else %}
            <input
                class="drest-field__input"
                name="{{ field.name }}"
                type="{% if style.input_type %}{{ style.input_type}}{% else %}text{% endif %}"
                id="{{ field.id }}-input"
                {% if field.read_only %}disabled{% endif %}
                {% if field.errors or field.help_text %}
                    aria-controls="{{ field.id }}-helper"
                    aria-describedby="{{ field.id }}-helper"
                {% endif %}
                {% if field.errors %}invalid{% endif %}
                {% if field.required %}required{% endif %}
                value={{ field | field_to_json }}
            />
        {% endif %}
        <label
            class="drest-label"
            for="{{ field.id }}-input"
        >
            {{ field.label }}
        </label>
        <div class="mdc-line-ripple" data-mdc-auto-init="MDCLineRipple"></div>
    </div>
    <p
        id="{{ field.id }}-helper"
        class="drest-field__helper">
        {% if field.help_text %}
            {{ field.help_text | help_text_format | safe }}
        {% endif %}
    </p>
    {% include "./field-js.html" %}
</div>

dynamic_rest/templates/dynamic_rest/login.html
{% extends "dynamic_rest/admin.html" %}
{% load staticfiles %}
{% load rest_framework %}
{% load dynamic_rest %}

{% block header_nav %}
    <span class="material-icons mdc-top-app-bar__navigation-icon">lock_open</span>
{% endblock %}

{% block header_content %}
    {% drest_settings 'API_NAME' %}
{% endblock %}

{% block content %}
    <div id="drest-content-container">
        <div class="drest-content">
            <form
                action="{% url 'dynamic_rest:login' %}"
                role="form"
                class="drest-form"
                method="post"
            >
              {% csrf_token %}
              <div class="drest-grid--1x drest-grid">
              <div class="drest-grid__item">
              <div class="drest-section">
              <div class="mdc-card__fields py-0">
                    <input type="hidden" name="next" value="{{ next }}">

                    <div class="drest-field">
                        <div class="{% if form.username.errors %}mdc-text-field--invalid{% endif %} mdc-text-field mdc-text-field--fullwidth" data-mdc-auto-init="MDCTextField">
                            <input
                                class="mdc-text-field__input drest-field__input"
                                name="username"
                                type="text"
                                id="username-input"
                                {% if form.username.errors %}
                                    aria-controls="username-helper"
                                    aria-describedby="username-helper"
                                {% endif %}
                                {% if form.username.errors %}
                                    invalid
                                {% endif %}
                                {% if form.username.value %}
                                    value={{ form.username.value }}
                                {% endif %}
                                required
                            />
                            <label class="mdc-floating-label mdc-floating-label" data-mdc-auto-init="MDCFloatingLabel" for="username-input">Username</label>
                            <div class="mdc-line-ripple" data-mdc-auto-init="MDCLineRipple"></div>
                        </div>
                        <p id="username-helper" class="{% if form.username.errors %}mdc-text-field-helper-text--validation-msg {% endif %}mdc-text-field-helper-text" aria-hidden="{% if form.username.errors %}false{% else %}true{% endif %}">
                            {% if form.username.errors %}
                                {% for error in form.username.errors %}
                                    <span>{{error}}</span>
                                {% endfor %}
                            {% endif %}
                        </p>
                    </div>
                    <div class="drest-field">
                        <div class="{% if form.password.errors %}mdc-text-field--invalid{% endif %} mdc-text-field mdc-text-field--fullwidth" data-mdc-auto-init="MDCTextField">
                            <input
                                class="mdc-text-field__input drest-field__input"
                                name="password"
                                type="password"
                                id="password-input"
                                {% if form.password.value %}
                                    value={{ form.password.value }}
                                {% endif %}
                                {% if form.password.errors %}
                                    aria-controls="password-helper"
                                    aria-describedby="password-helper"
                                {% endif %}
                                {% if form.password.errors %}
                                    invalid
                                {% endif %}
                                required
                            />
                            <label class="mdc-floating-label mdc-floating-label" data-mdc-auto-init="MDCFloatingLabel" for="password-input">Password</label>
                            <div class="mdc-line-ripple" data-mdc-auto-init="MDCLineRipple"></div>
                        </div>
                        <p id="password-helper" class="{% if form.password.errors %}mdc-text-field-helper-text--validation-msg {% endif %}mdc-text-field-helper-text" aria-hidden="{% if form.password.errors %}false{% else %}true{% endif %}">
                            {% if form.password.errors %}
                                {% for error in form.password.errors %}
                                    <div>{{error}}</div>
                                {% endfor %}
                            {% endif %}
                        </p>
                    </div>


                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <div class="p-2 text-danger">{{ error }}</div>
                        {% endfor %}
                    {% endif %}

                    <button type="submit" class="w-100 mdc-button mdc-button--raised">Log in</button>
                </div>
                </div>
                {% block other_login_options %}
                {% endblock %}
                </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}